---
title: "Grass biomass"
editor: visual
author: Taps
format: 
  html:
    colorlinks: true
    toc: true
    toc-depth: 3
    code-fold: true
---

## Introduction

The plots below show the relationship between DPM heights and standing biomass (kg/ha).

## Standing grass biomass at Shangani Holistic Ranch

```{r, warning=FALSE, message=FALSE, fig.cap="Figure 1. Strong relationship between DPM height and standing grass biomass at Shangani Holistic Ranch"}

library(tidyverse)
library(lmerTest)
library(ggplot2)
library(dplyr)
library(Matrix)
library(lme4)
library(emmeans)
library(here) ## MOST IMPORTANT NOT TO FORGET THIS ONE
library(robustbase)
library(sjPlot)

theme_beautiful <- function() {
  theme_bw() +
    theme(
      text = element_text(family = "Helvetica"),
      axis.text = element_text(size = 8, color = "black"),
      axis.title = element_text(size = 8, color = "black"),
      axis.line.x = element_line(size = 0.3, color = "black"),
      axis.line.y = element_line(size = 0.3, color = "black"),
      axis.ticks = element_line(size = 0.3, color = "black"),
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.y = element_blank(),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
      plot.title = element_text(
        size = 8,
        vjust = 1,
        hjust = 0.5,
        color = "black"
      ),
      legend.text = element_text(size = 8, color = "black"),
      legend.title = element_text(size = 8, color = "black"),
      legend.position = c(0.9, 0.9),
      legend.key.size = unit(0.9, "line"),
      legend.background = element_rect(
        color = "black",
        fill = "transparent",
        size = 2,
        linetype = "blank"
      )
    )
}

WGdata <- read_csv(here("DATA/DPM.csv"))

################## DPM HEIGHT ~ OVEN DRIED WEIGHT. NO SQUARE ROOT
# 2. Convert weight from grams to kg/ha
#    Area of 34cm diameter disc = π * (0.17 m)^2 = 0.0908 m²
frame_area <- pi * (0.17^2)  # = 0.0908 m²
WGdata$Biomass_kg_ha <- WGdata$Weight * 10 / frame_area

# 3. Linear regression: Biomass ~ DPH
modelWG <- lm(Biomass_kg_ha ~ DPH_Height, data = WGdata)
#summary(modelWG)
tab_model(modelWG)

### EQUATION FOR THE MODEL AND ANNOTATION
# Extract coefficients
    coefs <- coef(modelWG)
   intercept <- round(coefs[1], 2)
    slope <- round(coefs[2], 2)
 
 # Create equation string for annotation
 # Build the equation string (biomass = intercept + slope * x)
     eq <- paste0("Biomass== ", intercept, " + ", slope, " %*% Dpm")
 
 # Plot with regression and equation
 ggplot(WGdata, aes(x = DPH_Height, y = Biomass_kg_ha)) +
   geom_point() +
   geom_smooth(method = "lm", se = TRUE, color = "red") +
   annotate("text", x = min(WGdata$DPH_Height, na.rm = TRUE), 
            y = max(WGdata$Biomass_kg_ha, na.rm = TRUE), 
          label = eq, parse = TRUE, hjust = 0, size = 3, color = "red") +
   labs(
     x = "Dpm height (cm)",
     y = "Standing grass biomass (kg/ha)"
   ) +
   theme_beautiful()
 

```

```{r, warning=FALSE, message=FALSE, fig.cap="Figure 2. Comparing the Trollope model and SHR model using square root DPM height"}

library(tidyverse)
library(lmerTest)
library(ggplot2)
library(dplyr)
library(Matrix)
library(lme4)
library(emmeans)
library(here) ## MOST IMPORTANT NOT TO FORGET THIS ONE
library(robustbase)
library(sjPlot)

theme_beautiful <- function() {
  theme_bw() +
    theme(
      text = element_text(family = "Helvetica"),
      axis.text = element_text(size = 8, color = "black"),
      axis.title = element_text(size = 8, color = "black"),
      axis.line.x = element_line(size = 0.3, color = "black"),
      axis.line.y = element_line(size = 0.3, color = "black"),
      axis.ticks = element_line(size = 0.3, color = "black"),
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.y = element_blank(),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
      plot.title = element_text(
        size = 8,
        vjust = 1,
        hjust = 0.5,
        color = "black"
      ),
      legend.text = element_text(size = 8, color = "black"),
      legend.title = element_text(size = 8, color = "black"),
      legend.position = c(0.9, 0.9),
      legend.key.size = unit(0.9, "line"),
      legend.background = element_rect(
        color = "black",
        fill = "transparent",
        size = 2,
        linetype = "blank"
      )
    )
}

WGdata <- read_csv(here("DATA/DPM.csv"))


################## DPM HEIGHT ~ OVEN DRIED WEIGHT. NO SQUARE ROOT
# 2. Convert weight from grams to kg/ha
#    Area of 34cm diameter disc = π * (0.17 m)^2 = 0.0908 m²
frame_area <- pi * (0.17^2)  # = 0.0908 m²
WGdata$Biomass_kg_ha <- WGdata$Weight * 10 / frame_area

# 3. Linear regression: Biomass ~ DPH
modelWG <- lm(Biomass_kg_ha ~ DPH_Height, data = WGdata)


### USING THE TROLLOPE EQUATION TO COMPARE IT WITH MY MODEL
# Step 1: Prepare WGdata

WGdata$sqrtDPH_Height <- sqrt(WGdata$DPH_Height)

# Step 2: Create theoretical model predictions using the equation
WGdata$TR_model <- -3019 + 2260 * WGdata$sqrtDPH_Height

# Step 3: Theoretical model: y = -3019 + 2260 * sqrt(DP)
TR_model_data <- data.frame(
  sqrtDPH_Height = WGdata$sqrtDPH_Height,
  Biomass_kg_ha = -3019 + 2260 * WGdata$sqrtDPH_Height,
  Source = "Trollope and Potgieter 1986")

# Step 4: Add source to WGdata
WG_actual_data <- data.frame(
  sqrtDPH_Height = WGdata$sqrtDPH_Height,
  Biomass_kg_ha = WGdata$Biomass_kg_ha,
  Source = "SHR")

# Step 5: Combine both for plotting
combined <- rbind(WG_actual_data, TR_model_data)

# Step 6: Plot with legend
ggplot(combined, aes(x = sqrtDPH_Height, y = Biomass_kg_ha, color = Source)) +
  geom_point(data = subset(combined, Source == "SHR"), size = 2) +
  geom_smooth(data = subset(combined, Source == "SHR"),
              method = "lm", se = FALSE) +
  geom_line(data = subset(combined, Source == "Trollope and Potgieter 1986"),
            linetype = "dashed", size = 1) +
  labs(
    x = "Square root DPM height (cm)",
    y = "Standing Biomass (kg/ha)",
    color = "Model"
  ) +
  theme_beautiful() + theme(legend.position = "right") + 
  theme(
    legend.position = c(0.1, 1),
    legend.justification = c(0, 1),
    legend.box.just = "left",
    legend.title = element_text(face = "bold"),
    legend.background = element_rect(fill = "white", color = "gray90"))


```

```{r, warning=FALSE, message=FALSE, fig.cap="Figure 3. Comparing the Trollope model and SHR model using untransformed DPM height"}

library(tidyverse)
library(lmerTest)
library(ggplot2)
library(dplyr)
library(Matrix)
library(lme4)
library(emmeans)
library(here) ## MOST IMPORTANT NOT TO FORGET THIS ONE
library(robustbase)
library(sjPlot)

theme_beautiful <- function() {
  theme_bw() +
    theme(
      text = element_text(family = "Helvetica"),
      axis.text = element_text(size = 8, color = "black"),
      axis.title = element_text(size = 8, color = "black"),
      axis.line.x = element_line(size = 0.3, color = "black"),
      axis.line.y = element_line(size = 0.3, color = "black"),
      axis.ticks = element_line(size = 0.3, color = "black"),
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.y = element_blank(),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
      plot.title = element_text(
        size = 8,
        vjust = 1,
        hjust = 0.5,
        color = "black"
      ),
      legend.text = element_text(size = 8, color = "black"),
      legend.title = element_text(size = 8, color = "black"),
      legend.position = c(0.9, 0.9),
      legend.key.size = unit(0.9, "line"),
      legend.background = element_rect(
        color = "black",
        fill = "transparent",
        size = 2,
        linetype = "blank"
      )
    )
}

UGdata <- read_csv(here("DATA/DPM.csv"))
# 2. Convert weight from grams to kg/ha
#    Area of 34cm diameter disc = π * (0.17 m)^2 = 0.0908 m²
frame_area <- pi * (0.17^2)  # = 0.0908 m²
UGdata$Biomass_kg_ha <- UGdata$Weight * 10 / frame_area

# # Step 2: Add WG Data and TR Model as long-format data
UG_actual_data <- data.frame(
  DPH_Height = UGdata$DPH_Height,
  Biomass_kg_ha = UGdata$Biomass_kg_ha,
  Source = "SHR",
  stringsAsFactors = FALSE)


# # Step 3: Create TR model data using sqrt(DPH)
TR_model_data <- data.frame(
  DPH_Height = UGdata$DPH_Height,
  Biomass_kg_ha = -3019 + 2260 * sqrt(UGdata$DPH_Height),
  Source = "Trollope and Potgieter 1986",
  stringsAsFactors = FALSE)

# Step 4: Combine datasets
combined <- rbind(UG_actual_data, TR_model_data)

# Step 5: Plot both datasets without filtering (no subset!)
ggplot(combined, aes(x = DPH_Height, y = Biomass_kg_ha, color = Source)) +
  geom_point(data = UG_actual_data, size = 2) +  # scatter for UG
  geom_smooth(data = UG_actual_data, method = "lm", se = FALSE) +  # fit for UG
  geom_line(data = TR_model_data, linetype = "dashed", size = 1) +  # line for TR
  labs(
    x = "DPM height (cm)",
    y = "Standing Biomass (kg/ha)",
    color = "Model"
  ) +
  theme_beautiful() + 
  theme(
    legend.position = c(0.1, 1),
    legend.justification = c(0, 1),
    legend.box.just = "left",
    legend.title = element_text(face = "bold"),
    legend.background = element_rect(fill = "white", color = "gray90"))


```

```{r, warning=FALSE, message=FALSE, fig.cap="Figure 4. Comparing SHR model to two existing models previously used at Shangani Holistic Ranch"}
library(tidyverse)
library(lmerTest)
library(ggplot2)
library(dplyr)
library(Matrix)
library(lme4)
library(emmeans)
library(here) ## MOST IMPORTANT NOT TO FORGET THIS ONE
library(robustbase)
library(sjPlot)

theme_beautiful <- function() {
  theme_bw() +
    theme(
      text = element_text(family = "Helvetica"),
      axis.text = element_text(size = 8, color = "black"),
      axis.title = element_text(size = 8, color = "black"),
      axis.line.x = element_line(size = 0.3, color = "black"),
      axis.line.y = element_line(size = 0.3, color = "black"),
      axis.ticks = element_line(size = 0.3, color = "black"),
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.y = element_blank(),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
      plot.title = element_text(
        size = 8,
        vjust = 1,
        hjust = 0.5,
        color = "black"
      ),
      legend.text = element_text(size = 8, color = "black"),
      legend.title = element_text(size = 8, color = "black"),
      legend.position = c(0.9, 0.9),
      legend.key.size = unit(0.9, "line"),
      legend.background = element_rect(
        color = "black",
        fill = "transparent",
        size = 2,
        linetype = "blank"
      )
    )
}

#FITTING THE DRIED BIOMASS  TO THE OTHER TWO EXISTING MODELS  AND INCLUDING        #ANNOTATTIONS######

# Load and prepare data 

df <- read_csv(here("DATA/March2025/SHR_modelYear.csv"))

df$Year <- as.factor(df$Year)
df$Dpm <- as.numeric(as.character(df$Dpm))
df <- df[is.finite(df$Dpm), ]

# Define the range for Dpm values (based on your actual data)
dpm_range <- range(df$Dpm, na.rm = TRUE)

# Create a sequence of Dpm values across the range
dpm_vals <- seq(dpm_range[1], dpm_range[2], length.out = 100)

# Define the custom line (TER model)
custom_line <- data.frame(
  Dpm = dpm_vals,
  Biomass = 107.06 + 171.69 * dpm_vals,
  Year = "SHR")

df_combined <- rbind(
  df[, c("Dpm", "Biomass", "Year")],
  custom_line)

# Fit models for 2014 and 2015
model_2024 <- lm(Biomass ~ Dpm, data = subset(df, Year == "2024"))
model_2025 <- lm(Biomass ~ Dpm, data = subset(df, Year == "2025"))
#tab_model(model_2024)
#tab_model(model_2025)


# Extract and round coefficients
coef_2024 <- round(coef(model_2024), 2)
coef_2025 <- round(coef(model_2025), 2)
coef_SHR  <- c(171.69, 107.06)  # slope, intercept as per your earlier custom line

# Format equations as: biomass = slope + intercept * dpm
eq_2024 <- paste0("Biomass = ", coef_2024[2], " + ", coef_2024[1], " * Dpm")
eq_2025 <- paste0("Biomass = ", coef_2025[2], " + ", coef_2025[1], " * Dpm")
eq_SHR  <- paste0("Biomass = ", coef_SHR[1], " + ", coef_SHR[2], " * Dpm")

# Plot

ggplot(df_combined, aes(x = Dpm, y = Biomass, color = Year)) +
  geom_point(data = df) +
  geom_smooth(data = df, method = "lm", se = FALSE) +
  geom_line(data = custom_line, linetype = "solid", size = 1) +
  scale_color_manual(values = c("2024" = "green", "2025" = "purple", "SHR" = "red")) +
  labs(x = "DPM height (cm)", y = "Standing grass biomass (kg/ha)", color = "Model") +
  
  # Annotations to far left, stacked vertically
  annotate("text", x = 25, y = 2800, label = eq_2024, hjust = 0, color = "green", size = 4) +
  annotate("text", x = 25, y = 2200, label = eq_2025, hjust = 0, color = "purple", size = 4) +
  annotate("text", x = 25, y = 1600, label = eq_SHR, hjust = 0, color = "red", size = 4) +
  theme_beautiful()+ 
  theme(
    legend.position = c(0, 1),
    legend.justification = c(0, 0.8),
    legend.box.just = "left")

```

```{r, warning=FALSE, message=FALSE, fig.cap="Figure 5. Comparing SHR model to three models, two of them have been previously used at Shangani Holistic Ranch and the third is the Trollope model widely used in literature."}
library(tidyverse)
library(lmerTest)
library(ggplot2)
library(dplyr)
library(Matrix)
library(lme4)
library(emmeans)
library(here) ## MOST IMPORTANT NOT TO FORGET THIS ONE
library(robustbase)
library(sjPlot)

theme_beautiful <- function() {
  theme_bw() +
    theme(
      text = element_text(family = "Helvetica"),
      axis.text = element_text(size = 8, color = "black"),
      axis.title = element_text(size = 8, color = "black"),
      axis.line.x = element_line(size = 0.3, color = "black"),
      axis.line.y = element_line(size = 0.3, color = "black"),
      axis.ticks = element_line(size = 0.3, color = "black"),
      panel.border = element_blank(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.minor.y = element_blank(),
      panel.grid.major.y = element_blank(),
      plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
      plot.title = element_text(
        size = 8,
        vjust = 1,
        hjust = 0.5,
        color = "black"
      ),
      legend.text = element_text(size = 8, color = "black"),
      legend.title = element_text(size = 8, color = "black"),
      legend.position = c(0.9, 0.9),
      legend.key.size = unit(0.9, "line"),
      legend.background = element_rect(
        color = "black",
        fill = "transparent",
        size = 2,
        linetype = "blank"
      )
    )
}

#FITTING THE DRIED BIOMASS  TO THE OTHER THREE MODELS  AND INCLUDING        #ANNOTATTIONS######

# Load and prepare data 

df <- read_csv(here("DATA/March2025/SHR_modelYear.csv"))


#### FOUR MODELS INCLUDING ANNOTATIONS
#df$Year <- as.factor(df$Year)
df$Dpm <- as.numeric(as.character(df$Dpm))
df <- df[is.finite(df$Dpm), ]

df$Year <- as.factor(df$Year)
df$Dpm <- as.numeric(as.character(df$Dpm))
df <- df[is.finite(df$Dpm), ]

# Define the range for Dpm values (based on your actual data)
dpm_range <- range(df$Dpm, na.rm = TRUE)

# Create a sequence of Dpm values across the range
dpm_vals <- seq(dpm_range[1], dpm_range[2], length.out = 100)

# Define the custom line (SHR model)
custom_line <- data.frame(
  Dpm = dpm_vals,
  Biomass = 107.06 + 171.69 * dpm_vals,
  Year = "SHR")

# Ddefine Trollope line
trollope_line <- data.frame(
  Dpm = dpm_vals,
  Biomass = -3019 + 2260 * sqrt(dpm_vals),
  Year = "Trollope and Potgieter 1986")

#df_combined <- rbind(
# df[, c("Dpm", "Biomass", "Year")],
#custom_line, trollope_line)

df_combined <- rbind(
  df_combined,
  trollope_line)

# Fit models for 2014 and 2015
model_2024 <- lm(Biomass ~ Dpm, data = subset(df, Year == "2024"))
model_2025 <- lm(Biomass ~ Dpm, data = subset(df, Year == "2025"))
#tab_model(model_2024)
#tab_model(model_2025)


# Extract and round coefficients
coef_2024 <- round(coef(model_2024), 2)
coef_2025 <- round(coef(model_2025), 2)
coef_SHR  <- c(171.69, 107.06)  # slope, intercept as per your earlier custom line
coef_Trollope <- c(-3019, 2260)

# Format equations as: biomass = slope + intercept * dpm
eq_2024 <- paste0("Biomass = ", coef_2024[2], " + ", coef_2024[1], " * Dpm")
eq_2025 <- paste0("Biomass = ", coef_2025[2], " + ", coef_2025[1], " * Dpm")
eq_SHR  <- paste0("Biomass = ", coef_SHR[1], " + ", coef_SHR[2], " * Dpm")
eq_Trollope <- paste0("Biomass = ", round(coef_Trollope[1], 2), 
                      " + ", round(coef_Trollope[2], 2), " * sqrt(Dpm)")

##PLOT AND ANNOTATION

ggplot(df_combined, aes(x = Dpm, y = Biomass, color = Year)) +
  geom_point(data = df) +
  geom_smooth(data = df, method = "lm", se = FALSE) +
  geom_line(data = custom_line, linetype = "solid", size = 1) +
  geom_line(data = trollope_line, aes(x = Dpm, y = Biomass, color = "Trollope"),
            linetype = "dashed", size = 1) +  # <--- ADD THIS
  
  scale_color_manual(values = c(
    "2024" = "green",
    "2025" = "purple",
    "Trollope" = "blue",
    "SHR" = "red"
  )) +
  
  labs(x = "DPM height (cm)", y = "Standing grass biomass (kg/ha)", color = "Model") +
  
  # Annotations (including Trollope)
  annotate("text", x = 25, y = 2800, label = eq_2024, hjust = 0, color = "green", size = 4) +
  annotate("text", x = 25, y = 2000, label = eq_2025, hjust = 0, color = "purple", size = 4) +
  annotate("text", x = 25, y = 1200, label = eq_SHR, hjust = 0, color = "red", size = 4) +
  annotate("text", x = 25, y = 500, label = eq_Trollope, hjust = 0, color = "blue", size = 4) +
  
  theme_beautiful()+ 
  theme(
    legend.position = c(0, 1),
    legend.justification = c(0, 0.8),
    legend.box.just = "left")

```
